version: "3"

services:
  api:
    container_name: api
    build: .
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - redis
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  redis:
    image: redis:6-alpine
    restart: always
    container_name: redis
    command: redis-server
    ports:
      - 6379:6379
